# Development environment overrides
collection:
  max_papers_per_source: 20
  days_back: 30

models:
  ollama:
    model_name: "llama3.2:1b"  # Smaller model for dev
    
logging:
  level: "DEBUG"
  file: "logs/development.log"

output:
  base_dir: "dev_output"
