# Production environment overrides
collection:
  rate_limit: 0.5  # Faster in production
  max_papers_per_source: 500

models:
  embedding:
    batch_size: 64  # Larger batches in production

analysis:
  clustering:
    n_neighbors: 25
    min_cluster_size: 5

logging:
  level: "INFO"
  file: "logs/production.log"

resources:
  max_memory_gb: 16
  max_concurrent_requests: 10
